function listBoxHandle = SelectionPanel(figHandle)
% =========================================================================
% SelectionPanel: creates a side panel containing a listbox to display
% and manage selected poles, along with a legend panel.
%
% INPUT:
%   figHandle      : handle of the main figure
%
% OUTPUT:
%   listBoxHandle  : handle of the listbox UI for selected poles
% =========================================================================

% --- Create main panel for pole selection ---
panel = uipanel('Parent', figHandle, 'Units','normalized', ...
                'Position',[0.0015 0.25 0.104 0.60], 'Title','');

% --- Add panel title ---
uicontrol('Parent', panel, 'Style','text','Units','normalized', ...
          'Position',[0.05 0.93 0.9 0.05], ...
          'String','Selected poles', ...
          'FontSize',12,'FontWeight','bold', ...
          'HorizontalAlignment','center');

% --- Add instruction text ---
% Indicates how to remove a pole from the selection
uicontrol('Parent', panel, 'Style','text','Units','normalized', ...
          'Position',[0.05 0.88 0.9 0.04], ...
          'String','Left-click a pole to remove it', ...
          'FontSize',9, ...
          'HorizontalAlignment','center');

% --- Create listbox for selected poles ---
% Displays selected poles and allows interaction via callback
listBoxHandle = uicontrol('Parent', panel, 'Style','listbox', ...
                          'Units','normalized', ...
                          'Position',[0.05 0.05 0.9 0.82], ...
                          'String', {}, ...
                          'Callback', @(src,~,~) ...
                              removeSelectedPole(src, figHandle));

% ---------------------- Create compact legend panel ----------------------

panelLegend = uipanel('Parent', figHandle, ...
                      'Units', 'normalized', ...
                      'Position', [0.93 0.75 0.06 0.15], ... % narrow panel
                      'Title', 'Legend', ...
                      'FontSize', 9, ...
                      'FontWeight', 'bold');

% --- Define layout parameters for legend entries ---
blockHeight = 0.30;  % height of each legend block
spacingTop  = 0.02;  % spacing from top of panel

% --- Stable poles (s) ---
% Indicates poles with stable frequency and damping
uicontrol('Parent', panelLegend, 'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.05 1 - spacingTop - 1*blockHeight 0.9 blockHeight], ...
    'String', sprintf('s : Damping and\nFrequency Stable'), ...
    'FontSize', 9.2, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', 'g');

% --- Damping unstable poles (d) ---
% Indicates poles with unstable damping
uicontrol('Parent', panelLegend, 'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.05 1 - spacingTop - 2*blockHeight 0.9 blockHeight], ...
    'String', sprintf('d : Damping\nunstable'), ...
    'FontSize', 9.2, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', 'b');

% --- Frequency unstable poles (f) ---
% Indicates poles with unstable frequency
uicontrol('Parent', panelLegend, 'Style', 'text', ...
    'Units', 'normalized', ...
    'Position', [0.05 1 - spacingTop - 3*blockHeight 0.9 blockHeight], ...
    'String', sprintf('f : Frequency\nunstable'), ...
    'FontSize', 9.2, ...
    'HorizontalAlignment', 'left', ...
    'ForegroundColor', 'r');

end